### ISSUE TITLE
Go Medium

### ISSUE THREAD

**Issue by abitrolly** [opendataby/website#26]
Сейчас в блог могут писать только люди с доступом к Друпалу, и это работает не очень, потому что людей, которые работают с открытыми данными в РБ и могут поделиться гораздо больше. Medium позволяет вести Publication для нескольких людей.
https://help.medium.com/hc/en-us/articles/115012095528-About-Medium-publications
https://medium.com/@aytekin.tank/how-to-add-someone-as-writer-on-medium-215f0ef6117c

Да, это не собственная платформа. Но т.к. пока у нас мало людей со свободным временем, чтобы выстроить и поддерживать свою независмую инфраструктуру, приходится использовать GitHub, Google Groups и др. не очень открытые сервиы. )

**Comment by gsk990** [comment]
да ладно, забрать посты можно за день-два вручную :)

@abitrolly зарегишь учётную запись на медиуме, я займусь контентом?

**Comment by abitrolly** [comment]
Гатова. :D

**Comment by abitrolly** [comment]
medium.com, к сожалению, периодически просит денег у читателей, поэтому думаю надо его прикрыть. Никто не против?

**Comment by meramo** [comment]
Я подписчик медиума, так что смогу читать посты ) Но вообще да, как-то не очень, давайте прикроем

**Comment by abitrolly** [comment]
Done.
