### ISSUE TITLE
Редирект на https и поправить ссылку в описании

### ISSUE THREAD

**Issue by abitrolly** [opendataby/website#29]
![image](https://user-images.githubusercontent.com/8781107/68472944-b8c8a900-0232-11ea-8651-f7ca1080e11c.png)

![image](https://user-images.githubusercontent.com/8781107/68472987-dac22b80-0232-11ea-93bd-11ac9c7d51d7.png)

:/ как-то неаккуратненько

**Comment by gsk990** [comment]
Старая версия ОС на сервере, поэтому нет возможности сделать обновление letsencrypt сертификата. Планируем с Егором на следующей неделе новый хостинг наконец настроить с последней убунтой, переехать туда и уже жить с нормальным сертификатом

**Comment by abitrolly** [comment]
Хотите поменять Digital Ocean или просто заняться миграцией на другой дроплет?

**Comment by gsk990** [comment]
Другой дроплет на ДО

**Comment by abitrolly** [comment]
Может сразу запишете по шагам, что делали, чтобы можно было инструкции применить для разработки на локальном сервере?

**Comment by abitrolly** [comment]
Хотя в README.md что-то ж есть.

**Comment by gsk990** [comment]
итак, новый дроплет со всем новым И ОБНОВЛЁН софт для letsencrypt, таким образом пофикшен HTTPS/SSL!!!!

![image](https://user-images.githubusercontent.com/1129775/70705685-87d20d00-1ce5-11ea-8912-fef6ece66694.png)


full changelog:
LEMP on 18.04
backups enabled
Updated Core and 33 modules (list attached on image).
Comment Edit
Backup and Migrate 7.x-3.6
Double Field 7.x-2.5
Internationalization 7.x-1.26
Job Scheduler 7.x-2.0
Pathauto 7.x-1.3
Redirect 403 to User Login 7.x-1.8
Remote stream wrapper 7.x-1.0
Semantic Views 7.x-1.1
Views Bulk Operations (VBO) 7.x-3.5
Views Autocomplete Filters 7.x-1.2
Views Reference Filter 7.x-1.7
Comment Edit
Search API 7.x-1.26
Search API Database Search 7.x-1.7
Semantic Views 7.x-1.1
Simple Google Maps 7.x-1.4
Views Slideshow 7.x-3.9
Menu Token 7.x-1.0-beta7
Entity Construction Kit (ECK) 7.x-2.0-rc10
File Entity (fieldable files) 7.x-2.27
Admin role 7.x-1.1
Chosen 7.x-2.1
IMCE 7.x-1.11
CKEditor - WYSIWYG HTML editor 7.x-1.18
Drop Guard - DELETED.
Markdown 7.x-1.5
Markdown editor for BUEditor 7.x-1.4
Исправлено Error: Class 'ZipArchive' not found в функции _dkan_dataset_zip()

![image](https://user-images.githubusercontent.com/1129775/70706146-6faebd80-1ce6-11ea-98ac-760b6f155f10.png)

**Comment by abitrolly** [comment]
Ну малайцы.

Может и DKAN получится обновить, а то GitHub ругается - https://github.com/opendataby/website/network/alerts
