### ISSUE TITLE
Рассылка и группа?

### ISSUE THREAD

**Issue by abitrolly** [opendataby/website#4]
http://opendata.by/subscribe - это чё вообще? :confused:

**Comment by meramo** [comment]
Это рассылка по емэйл. Рассылка в плане рассылка а не группа. Типа той что у нас для митапов.
Туда мы засовываем все емэйлы, которые были на наших ивэнтах, или подписались специально. Используется только для важных анонсов. Mailchimp

**Comment by abitrolly** [comment]
А почему мы не можем анонсы публичные делать с архивом?

**Comment by meramo** [comment]
В смысле в группу на гугл? можем, но идея была в том, чтобы не спамить людей, которые не сильно вовлечены в тему, но тем не менее хотят оставаться в курсе важнейших событий (ивэнтов, анонсов и т.п.) Поэтому рабочие обсуждения в группе, а важные анонсы в рассылке.

**Comment by abitrolly** [comment]
Что-то я не понимаю. У нас ведь есть блог, там новости. Есть группа - там
обсуждения. Зачем рассылка?

**Comment by abitrolly** [comment]
Короч, надо назвать текущую рассылку по-другому и дать ссылку на архив,
чтобы людям было понятно, как их спамить будут.

**Comment by meramo** [comment]
Поскольку рассылкой на Mailchimp мы вообще не пользуемся, слова "рассылка" и "гугл группа" пока могут быть синонимами.

**Comment by abitrolly** [comment]
Надо убирать рассылку из подвала или заменить её на прямой линк в гуглогруппу.
